Add copyright; don't touch ECC certs
git-svn-id: file:///home/svn/DVA2006@17624 1e6d2d28-e1fb-0310-b8ab-81908d8c6b6a

diff --git a/scripts/pri/add_ffdhe b/scripts/pri/add_ffdhe
--- a/scripts/pri/add_ffdhe
+++ b/scripts/pri/add_ffdhe
@@ -1,4 +1,6 @@
 #!/bin/bash
+# DHE parameter add script
+# (c) 2022 Global Virtual Airlines Group. All Rights Reserved.
 
 # Check for arguments
 if [ "$2" == "" ]
@@ -26,10 +28,24 @@ if [ $DH_CNT -ne 0 ]; then
 	exit 3
 fi
 
+# Check for the key file
+KEY_FILE=$(echo "$1" | sed "s/crt/key")
+if [ ! -f "$KEY_FILE" ]; then
+	echo "Cannot find $KEY_FILE"
+	exit 4
+fi
+
+# Check if the key file isn't ECC
+if [ "$KEY_FILE" == *".ecc."* ]; then
+	echo "$KEY_FILE is an ECC key"
+	exit 5
+fi
+
+# Create the temp file
 TMP_FILE=$(mktemp -q /tmp/bar.XXXXXX)
 if [ $? -ne 0 ]; then
     echo "$0: Can't create temp file"
-    exit 5
+    exit 6
 fi
 
 # Cleanup temp file
