Check that directories actually exist
git-svn-id: file:///home/svn/DVA2006@17485 1e6d2d28-e1fb-0310-b8ab-81908d8c6b6a

diff --git a/scripts/pri/svn_backup b/scripts/pri/svn_backup
--- a/scripts/pri/svn_backup
+++ b/scripts/pri/svn_backup
@@ -5,6 +5,12 @@
 # Set archiving options
 arc_util="pbzip2 -9 -p4 -c"
 
+# Check for folders
+if [ ! -d "/home/backup/svn" ] || [ ! -d "/home/svn" ] ;then
+ echo "Backup Paths not found!"
+ exit 1
+fi
+
 # Goto backup directory
 cd /home/backup/svn
 
diff --git a/scripts/sec/cfg_backup b/scripts/sec/cfg_backup
--- a/scripts/sec/cfg_backup
+++ b/scripts/sec/cfg_backup
@@ -1,6 +1,12 @@
 #!/bin/bash
 # Configuration backup script
-# (c) 2005, 2006, 2007, 2010, 2011, 2012, 2021 Global Virtual Airlines Group. All Rights Reserved.
+# (c) 2005, 2006, 2007, 2010, 2011, 2012, 2021, 2022 Global Virtual Airlines Group. All Rights Reserved.
+
+# Check for folders
+if [ ! -d "/home/backup/cfg" ] || [ ! -d "/home/backup/sites" ] ;then
+ echo "Backup Paths not found!"
+ exit 1
+fi
 
 # Goto backup directory
 cd /home/backup/cfg
